In [1]:
# Clear any logs from previous runs

In [2]:
import numpy as np
import pandas as pd
import time, os

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras.utils import to_categorical
from tensorboard.plugins.hparams import api as hp

from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.models import Model

from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.model_selection import train_test_split as split

import random
from math import floor
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import optimizers
from scipy.integrate import odeint
import scipy
import pandas as pd

In [3]:
np.random.seed(0)

tf.config.optimizer.set_jit(True)
scaler = StandardScaler()

In [4]:
#algorithm for splitting the dataset into training and validation 
def split(X,Y,porcent): #porcent must be between 0 and 1, it is the asigned porcent to the training dataset.
    n=floor(porcent*len(X))
    index=random.sample(range(len(X)),n)
    X_learn=[]
    Y_learn=[]
    for i in index:
        X_learn.append(X[i])
        Y_learn.append(Y[i])
    X_val=np.delete(X,index, axis=0)
    Y_val=np.delete(Y,index, axis=0)
    
    X_learn=np.array(X_learn)
    Y_learn=np.array(Y_learn)
    return X_learn,Y_learn,X_val,Y_val

In [5]:
O_m=np.arange(0.1,0.51,0.1)
H_0=np.arange(66,81,1)
t=np.linspace(0,-12,50)

In [6]:
def RHS(Omega_i, lna, gamma=0):
    x, y, z, H = Omega_i
    #x, y, z = Omega_i
    pi = 3*x + 4*y
    return [x*(-3 + pi), y*(-4 + pi), z*pi, -0.5*H*pi]
    #return [x*(-3 + pi), y*(-4 + pi), z*pi]

def EDO(t,Om,H0):
    #t,Or,Om,Ol=X
    Or=0.0001
    Ol=1-Or-Om
    #H0 = 70.
    y0 = [Om, Or, Ol, H0]
    result = odeint(RHS, y0, t)
    return result

In [7]:
#lets generate the cartesian product between the intervals
Y0=[]
#este ciclo llena la lista fijando un Om y pasando todos los Or
for i in O_m:
    for j in H_0:
        Y0.extend(EDO(t,i,j))
Y0=np.array(Y0)

X0=[]
for Om in O_m:
    for H0 in H_0:
        for T in t:
            X0.append([T,Om,H0])
X0=np.array(X0)

In [8]:
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler(feature_range = (0,1))
Y2 = scaler.fit_transform(Y0)

In [9]:
#Now, here are the datasets
print('feactures= \n',X0)
print('\n')
print('labels= \n',Y2)

feactures= 
 [[  0.           0.1         66.        ]
 [ -0.24489796   0.1         66.        ]
 [ -0.48979592   0.1         66.        ]
 ...
 [-11.51020408   0.5         80.        ]
 [-11.75510204   0.5         80.        ]
 [-12.           0.5         80.        ]]


labels= 
 [[9.47515373e-02 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [1.83608702e-01 1.41110961e-04 9.01997379e-01 1.62358493e-10]
 [3.22333902e-01 4.33937896e-04 7.48914062e-01 4.77144941e-10]
 ...
 [4.20164900e-02 9.58104047e-01 5.58400899e-11 3.78984027e-01]
 [3.19464665e-02 9.68145182e-01 5.73926010e-11 6.15280156e-01]
 [2.39153274e-02 9.76153281e-01 5.75107557e-11 1.00000000e+00]]


In [10]:
split_size = 0.8
X_train, Y_train, X_test, Y_test = split(X0, Y2, split_size)

### Hiperparámetros del modelo

In [11]:
# HP_NUM_UNITS3 = hp.HParam('num_units3', hp.Discrete([50, 100, 150, 200]))
# HP_NUM_UNITS4 = hp.HParam('num_units4', hp.Discrete([2, 5, 10]))
# HP_DROPOUT = hp.HParam('dropout', hp.RealInterval(0.0, 0.2))
# HP_OPTIMIZER = hp.HParam('optimizer', hp.Discrete(['adam', 'sgd']))
# HP_OPTIMIZER = hp.HParam('optimizer', hp.Discrete(['adam', 'Adadelta']))
# HP_OPTIMIZER = hp.HParam('optimizer', hp.Discrete(['adam']))
HP_BATCHSIZE = hp.HParam('batch_size', hp.Discrete([8, 16]))


HP_LAYERS =    hp.HParam('layers', hp.Discrete([1, 2, 3, 4]))
HP_NUM_UNITS = hp.HParam('num_units', hp.Discrete([50, 100, 150, 200]))
HP_LEARNING  = hp.HParam('learning_rate', hp.Discrete([1e-4,1e-3]))

callbacks = [tf.keras.callbacks.EarlyStopping(monitor='val_loss', mode='min',
                                   min_delta=0,
                                   patience=100,
                                   restore_best_weights=True)]
# batch_size = 128
epochs = 500

In [12]:
# METRIC_ACCURACY = 'accuracy'
with tf.summary.create_file_writer('logs/hparam_tuning2').as_default():
# with tf.summary.FileWriter('logs/hparam_tuning', sess.graph):
#     init = tf.initialize_all_variables()
#     sess.run(init)
    hp.hparams_config(
        hparams=[HP_LAYERS,
                 HP_NUM_UNITS,
                 HP_LEARNING, 
                 HP_BATCHSIZE],
        metrics=[hp.Metric('loss', display_name="Loss")])

In [13]:
def train_test_model(hparams):    
    
    # Train LSTM model and predict on validation set
    model = tf.keras.Sequential()
    model.add(Dense(int(X_train.shape[1])))
    
    for i in range(hparams[HP_LAYERS]):        
        model.add(Dense(hparams[HP_NUM_UNITS], activation='relu'))
    model.add(Dense(4, activation='linear'))
     
    optimizer = tf.keras.optimizers.Adam(learning_rate=hparams[HP_LEARNING], beta_1=0.9, beta_2=0.999, epsilon=1e-3)
    model.compile(
            optimizer=optimizer,
            loss='mse', 
            metrics=['mean_squared_error'])
    
    # Run with 1 epoch to speed things up for demo purposes

    model.fit(X_train, Y_train, epochs=epochs, validation_data=(X_test, Y_test),
              callbacks=callbacks, batch_size=hparams[HP_BATCHSIZE], shuffle=False, verbose=0)

    _, loss = model.evaluate(X_test, Y_test)
    
    return loss

In [14]:
def run(run_dir, hparams):
    with tf.summary.create_file_writer(run_dir).as_default():
        hp.hparams(hparams)  # record the values used in this trial
        loss = train_test_model(hparams)
        tf.summary.scalar("loss", loss, step=1)
        return loss

In [15]:
session_num = 0
datos = []
t0 = time.time()
for deep_layers in HP_LAYERS.domain.values:
    for num_units in HP_NUM_UNITS.domain.values:
        for learning_rate in HP_LEARNING.domain.values:
            for batch_size in HP_BATCHSIZE.domain.values:
                t = time.time()
                hparams = {

                    HP_LAYERS: deep_layers,
                    HP_NUM_UNITS: num_units,
                    HP_LEARNING: learning_rate,
                    HP_BATCHSIZE: batch_size,
                }
                run_name = "run-%d" % session_num
                print('\n--- Starting trial: %s' % run_name)
                print({h.name: hparams[h] for h in hparams})
                score = run('logs/hparam_tuning2/' + run_name, hparams)
                t = time.time()-t
                session_num += 1
                print("Loss:", score, "Tiempo transcurrido:", t)
            
            datos.append([deep_layers, num_units, learning_rate, batch_size, score, t])

print(session_num)
tf = time.time() - t0


--- Starting trial: run-0
{'layers': 1, 'num_units': 50, 'learning_rate': 0.0001, 'batch_size': 8}
24/24 [==============================] - 0s 1ms/step - loss: 0.0085 - mean_squared_error: 0.0085
Loss: 0.008543111383914948 Tiempo transcurrido: 236.4396116733551

--- Starting trial: run-1
{'layers': 1, 'num_units': 50, 'learning_rate': 0.0001, 'batch_size': 16}
24/24 [==============================] - 0s 1ms/step - loss: 0.0201 - mean_squared_error: 0.0201
Loss: 0.020129911601543427 Tiempo transcurrido: 132.40395164489746

--- Starting trial: run-2
{'layers': 1, 'num_units': 50, 'learning_rate': 0.001, 'batch_size': 8}
24/24 [==============================] - 0s 903us/step - loss: 5.0475e-04 - mean_squared_error: 5.0475e-04
Loss: 0.0005047536105848849 Tiempo transcurrido: 244.10622334480286

--- Starting trial: run-3
{'layers': 1, 'num_units': 50, 'learning_rate': 0.001, 'batch_size': 16}
24/24 [==============================] - 0s 927us/step - loss: 0.0024 - mean_squared_error: 0.0024

24/24 [==============================] - 0s 1ms/step - loss: 7.7936e-05 - mean_squared_error: 7.7936e-05
Loss: 7.793631812091917e-05 Tiempo transcurrido: 316.38970851898193

--- Starting trial: run-61
{'layers': 4, 'num_units': 200, 'learning_rate': 0.0001, 'batch_size': 16}
24/24 [==============================] - 0s 1ms/step - loss: 0.0013 - mean_squared_error: 0.0013
Loss: 0.001325038610957563 Tiempo transcurrido: 179.74763536453247

--- Starting trial: run-62
{'layers': 4, 'num_units': 200, 'learning_rate': 0.001, 'batch_size': 8}
24/24 [==============================] - 0s 1ms/step - loss: 4.4110e-05 - mean_squared_error: 4.4110e-05
Loss: 4.411049667396583e-05 Tiempo transcurrido: 314.2203879356384

--- Starting trial: run-63
{'layers': 4, 'num_units': 200, 'learning_rate': 0.001, 'batch_size': 16}
24/24 [==============================] - 0s 1ms/step - loss: 6.8318e-05 - mean_squared_error: 6.8318e-05
Loss: 6.831753125879914e-05 Tiempo transcurrido: 147.12055802345276
64


### Guardar datos

In [16]:
filename = "historial_ecsdiff_tunning.txt"
df = pd.DataFrame(datos, columns = ["Deep size", "Num units", "Learning rate", "Batch size", "MSE", "Tiempo de ejecución"])

df.sort_values(by=["MSE", "Tiempo de ejecución"], ascending=[True, True], ignore_index=True, inplace=True)

df.to_csv(filename, header=True, index=False, sep='\t', mode='w') # a=append, w=overwrite

In [17]:
df

Deep size  Num units  Learning rate  Batch size       MSE  \
0           2        150         0.0010          16  0.000036   
1           3        200         0.0010          16  0.000039   
2           4         50         0.0010          16  0.000057   
3           2        100         0.0010          16  0.000057   
4           3        100         0.0010          16  0.000059   
5           4        200         0.0010          16  0.000068   
6           4        100         0.0010          16  0.000068   
7           4        150         0.0010          16  0.000072   
8           2         50         0.0010          16  0.000096   
9           1        200         0.0010          16  0.000102   
10          2        200         0.0010          16  0.000182   
11          1        150         0.0010          16  0.000207   
12          3         50         0.0010          16  0.000263   
13          4        200         0.0001          16  0.001325   
14          4        100         0.0001          16  0.001703   
15          3        200         0.0001          16  0.001965   
16          4         50         0.0001          16  0.002066   
17          2        100         0.0001          16  0.002219   
18          3        150         0.0010          16  0.002364   
19          1         50         0.0010          16  0.002387   
20          4        150         0.0001          16  0.002703   
21          3        100         0.0001          16  0.002713   
22          2        200         0.0001          16  0.002964   
23          3        150         0.0001          16  0.003081   
24          1        150         0.0001          16  0.003416   
25          1        100         0.0010          16  0.003493   
26          3         50         0.0001          16  0.004356   
27          2        150         0.0001          16  0.005213   
28          1        200         0.0001          16  0.005341   
29          1        100         0.0001          16  0.005619   
30          2         50         0.0001          16  0.010001   
31          1         50         0.0001          16  0.020130   

    Tiempo de ejecución  
0            158.205716  
1            118.349954  
2            143.345954  
3            148.405932  
4            154.226264  
5            147.120558  
6            164.456506  
7            190.814214  
8            137.147581  
9            133.449949  
10           162.144380  
11           129.874874  
12           144.682124  
13           179.747635  
14           157.889147  
15           159.056441  
16           141.780751  
17           153.647026  
18           171.097041  
19           134.515417  
20           126.972232  
21           153.219090  
22           157.651839  
23           143.860930  
24           129.856317  
25           136.137341  
26           141.617151  
27           153.781749  
28           142.541013  
29           131.900684  
30           134.805383  
31           132.403952

In [18]:
print("Tiempo total: {:.2f} min".format(tf/60))

Tiempo total: 214.43 min


In [19]:
# rm -rf /tmp/tb_logs/

### Now in terminal:
`python3 -m tensorboard.main --logdir='/home/isidro/Documents/github/neurapprox/logs/hparam_tuning'`

In [20]:
!kill 7439
%tensorboard --logdir logs/hparam_tuning2

/usr/bin/sh: 1: kill: No such process



UsageError: Line magic function `%tensorboard` not found.
